### PR TITLE
#15 improved website UI and fellow card added

### PR DESCRIPTION
**Pull request by Abusayid693**
### Your checklist for this pull request

Screenshot 2021-10-08 at 8 31 09 PM

Screenshot 2021-10-08 at 8 31 39 PM
- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Screenshots
Add any images if required.

### CODE REVIEW

**Comment by riteshsp2000** [comment]
Hey! This looks amazing! The preloader is a cool touch!

**Comment by Abusayid693** [comment]
@yashika51 Please review new UI

**Comment by Shubham0324** [comment]
Hey, you can also add a button to schedule calendly meetings with pod members it would really come in handy in the coming weeks. Btw loves the UI.

**Comment by Abusayid693** [comment]
@Shubham0324 yeah sure that's a good idea will replace Insta with calendy

**Pull request merged**
